#pragma once

#include <space-shooter/ecs/systems/input_system.hpp>
#include <space-shooter/ecs/systems/movement_system.hpp>
#include <space-shooter/ecs/systems/rendering_system.hpp>
#include <space-shooter/ecs/systems/scene_system.hpp>
#include <space-shooter/ecs/systems/shooting_system.hpp>
#include <space-shooter/ecs/systems/clock_system.hpp>
#include <space-shooter/ecs/systems/enemy_spawn_system.hpp>
#include <space-shooter/ecs/systems/text_rendering_system.hpp>
#include <space-shooter/ecs/systems/timer_system.hpp>
#include <space-shooter/ecs/systems/switch_to_pause_menu_system.hpp>
#include <space-shooter/ecs/systems/collision_system.hpp>
#include <space-shooter/ecs/systems/enemy_chasing_system.hpp>
#include <space-shooter/ecs/systems/cleankilledship_system.hpp>
#include <space-shooter/ecs/systems/enemy_shooting_system.hpp>
#include <space-shooter/ecs/systems/healthbardisplay_system.hpp>
#include <space-shooter/ecs/systems/audio_system.hpp>
#include <space-shooter/ecs/systems/music_system.hpp>